name: Deploy React Vite to Hostinger

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm i --legacy-peer-deps

      - name: Build project
        run: npm run build

      - name: List build output
        run: ls -la dist || echo "dist folder missing"

      - name: Deploy build to branch
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git checkout main
          git checkout --orphan deploy-temp
          git rm -rf .
          mv ../dist/* . || echo "Error: dist folder empty"
          rm -rf ../dist
          git add .
          git commit -m "Deploy build $(date '+%Y-%m-%d %H:%M:%S')"
          git push origin deploy-temp:deploy -f
          git branch -D deploy-temp
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger Hostinger deploy
        run: curl -X POST ${{ secrets.HOSTINGER_WEBHOOK_URL }}
